name: fruityvice
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bottom_navy_bar: ^6.0.0
  flutter_svg: ^1.0.3
  rxdart: ^0.27.3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/image/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-Medium.ttf
        - asset: assets/font/Poppins-Regular.ttf
